# Generated by Django 4.1.7 on 2023-03-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='germination_temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='optimum_high_temp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='optimum_low_temp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
