# Generated by Django 4.1.7 on 2023-03-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenspace', '0002_alter_plant_germination_temperature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='scientific_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
