# Generated by Django 4.1.7 on 2023-03-10 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardenspace', '0003_alter_plant_scientific_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardenspace.plant')),
            ],
        ),
    ]
