# Generated by Django 4.1.7 on 2023-03-10 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gardenspace', '0004_myplant'),
    ]

    operations = [
        migrations.AddField(
            model_name='myplant',
            name='state',
            field=models.CharField(choices=[('unplanted', 'unplanted'), ('planted', 'planted')], default='unplanted', max_length=20),
        ),
        migrations.AddField(
            model_name='myplant',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
