# Generated by Django 4.1.7 on 2023-03-13 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gardenspace', '0006_rename_plant_id_myplant_plant_remove_myplant_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myplant',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
