# Generated by Django 4.1.7 on 2023-03-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenspace', '0011_remove_myplant_location_location_my_plants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='my_plants',
            field=models.ManyToManyField(related_name='locations', to='gardenspace.myplant'),
        ),
    ]
