# Generated by Django 4.1.7 on 2023-03-16 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gardenspace', '0012_alter_location_my_plants'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='my_plants',
            field=models.ManyToManyField(blank=True, related_name='locations', to='gardenspace.myplant'),
        ),
    ]
