# Generated by Django 4.1.7 on 2023-03-26 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardenspace', '0013_location_user_alter_location_my_plants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='my_plants',
        ),
        migrations.CreateModel(
            name='LocationMyPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardenspace.location')),
                ('my_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardenspace.myplant')),
            ],
            options={
                'db_table': 'gardenspace_location_my_plants',
                'ordering': ['id'],
            },
        ),
    ]
