# Generated by Django 4.1.7 on 2023-03-26 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardenspace', '0014_remove_location_my_plants_locationmyplant'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='locationmyplant',
            table=None,
        ),
    ]
